### ISSUE TITLE
Smaller UX Improvements

### ISSUE THREAD

**Issue by zaanposni** [zaanposni/psaggregator#24]
Based on [Reddit Feedback](https://www.reddit.com/r/PietSmiet/comments/1abjhgm/aggregationswebsite_und_maschinenlesbare_daten/)

- [x] add option to view advanced details in /videos (similar to new videos in home)
- [x] add option to navgiate through older uploadplans
- [x] new icon or other means of seperation in uploadplan for existing and pending videos
- [x] add option to make date values absolute instead of relative
- [x] mark external URLs in header/footer as such
- [x] ~~Make links in Insta/YT Posts clickable. Evaluate possible code injection here!~~

**Comment by Leseratte10** [comment]
Three additional things I noticed (and edited into my reddit comment): 

- It'd be cool if the upload plan would have links to both the Pietsmiet.de and the Youtube version of a video - if that's possible, no idea how difficult it'd be to figure out the Youtube URL.
- The website has no Imprint / Impressum because you say it's a private project only - I'm not sure if that applies given that there's a donation link.
- The Imprint link on your personal website is broken and leads to a scam / advertise website.

**Comment by zaanposni** [comment]
> The Imprint link on your personal website is broken and leads to a scam / advertise website.

Fixed! Thanks! That was a older domain of mine that I did not renew :o

> It'd be cool if the upload plan would have links to both the Pietsmiet.de and the Youtube version of a video - if that's possible, no idea how difficult it'd be to figure out the Youtube URL.

I wanted to do that too. In fact, my database table has a `secondaryHref` field for that purpose. The problem is that the linking is not as easy as one might think since the IDs of the videos are not properly shared on pietsmiet.de. Also, the pietsmiet.de internal API no longer returns the YouTube links. You might remember that the Uploadplan on pietsmiet.de has also shown the YouTube links over the last few years.

**Comment by zaanposni** [comment]
Closing for release 1.4.0
Pending issues in this thread are now seperate issues in #26 and #27

**Comment by Leseratte10** [comment]
Thanks, that was quick!

A couple things I noticed: 

In the new "complex view" for past videos, Umlaute (ÄÖÜẞäöüß) or any other special characters are broken. Also, the video length is not yet displayed like it is on the main page.

Also, can the box with the video title be made a bit smaller? There's quite a bit unnecessary empty vertical space between video title and video upload time.

EDIT: Also, the "complex view" toggle resets again when reloading the page, I'd move that to the settings page as well and make it permanent.
